# Podfile

platform :osx, '10.13.2'

use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
    pod 'Dollar'
    pod 'Combinatorics'
end

target 'CodingPractice' do
    pod 'SwiftyJSON'
#    testing_pods
end

target 'CodingPracticeTests' do
    testing_pods
end
